name: auna_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Te recomiendo usar una versiÃ³n estable

dependencies:
  flutter:
    sdk: flutter

  # --- Paquetes Esenciales ---
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

  # --- Paquetes para Funcionalidades ---
  table_calendar: ^3.1.1 
  intl: ^0.19.0 
  pdf: ^3.10.8                
  path_provider: ^2.1.3        
  open_file_plus: ^3.4.1  
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  google_nav_bar: ^5.0.6
  flutter_local_notifications: ^17.1.2
  uuid: ^4.4.0
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/